version: "3"

volumes:
  simpleblog_local_postgres_data: {}
  simpleblog_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: simpleblog_local_django
    container_name: simpleblog_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: simpleblog_production_postgres
    container_name: simpleblog_local_postgres
    volumes:
      - simpleblog_local_postgres_data:/var/lib/postgresql/data
      - simpleblog_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  pgadmin:
    container_name: simpleblog_local_pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5011:80"
    tty: true
    logging:
      driver: "none"

  docs:
    image: simpleblog_local_docs
    container_name: simpleblog_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./simpleblog:/app/simpleblog:z
    ports:
      - "9000:9000"
    command: /start-docs

  redis:
    image: redis:6
    container_name: simpleblog_local_redis

  celeryworker:
    <<: *django
    image: simpleblog_local_celeryworker
    container_name: simpleblog_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: simpleblog_local_celerybeat
    container_name: simpleblog_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: simpleblog_local_flower
    container_name: simpleblog_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
